language: ruby
cache: bundler
sudo: required

rvm:
  - 2.4.1

before_install:
  - sudo /etc/init.d/postgresql stop
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main 9.5" >> /etc/apt/sources.list.d/postgresql.list'
  - sudo apt-get update
  - sudo apt-get install postgresql-9.5
  - gem update --system
  - gem update bundler

before_script:
  - sudo /etc/init.d/postgresql stop
  - sudo cp /etc/postgresql/9.2/main/pg_hba.conf /etc/postgresql/9.5/main/pg_hba.conf
  - sudo sh -c 'echo "local all postgres trust" > /etc/postgresql/9.5/main/pg_hba.conf'
  - sudo sh -c 'echo -n "host all all 127.0.0.1/32 trust" >> /etc/postgresql/9.5/main/pg_hba.conf'
  - sudo /etc/init.d/postgresql start 9.5
  - psql --version
  - cp config/database.yml.travis config/database.yml
  - cp config/secrets.yml.sample config/secrets.yml

script:
  - RAILS_ENV=test bundle exec rake db:create
  - RAILS_ENV=test bundle exec rake db:migrate
  - 'CODECLIMATE_REPO_TOKEN=xxx xvfb-run bundle exec rspec'
  - bundle exec rubocop

notifications:
  email:
    recipients:
      - sebastian.schkudlara@vizzuality.com
    on_failure: change
    on_success: never

addons:
  code_climate:
    repo_token: xxx
